### ISSUE TITLE
Uncaught TypeError: Incorrect value of args option

### ISSUE THREAD

**Issue by pvince99** [idleberg/atom-build-python#10]
[Enter steps to reproduce:]

1. ...simple python program

print('hi')
import sys
print(sys.version)
import pygame
from pygame.base import *
print('all imported')

2. ... build, then as follows

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.10.3
**Thrown From**: [build-python](https://github.com/idleberg/atom-build-python) package 0.8.0

### Stack Trace

Uncaught TypeError: Incorrect value of args option

```
At child_process.js:328

TypeError: Incorrect value of args option
    at normalizeSpawnArguments (child_process.js:328:11)
    at spawnSync (child_process.js:420:38)
    at PythonProvider.isEligible (/packages/build-python/lib/provider.js:100:19)
    at /packages/build/lib/target-manager.js:68:30
    at Array.filter (native)
    at /packages/build/lib/target-manager.js:68:10
    at Array.map (native)
    at TargetManager.refreshTargets (/packages/build/lib/target-manager.js:58:39)
    at TargetManager.getTargets (/packages/build/lib/target-manager.js:216:19)
    at Object.startNewBuild (/packages/build/lib/build.js:111:40)
    at /packages/build/lib/build.js:270:14
    at saveAndContinue (/packages/build/lib/build.js:277:7)
    at Object.doSaveConfirm (/packages/build/lib/build.js:281:7)
    at Object.build (/packages/build/lib/build.js:264:10)
    at /packages/build/lib/build.js:25:69)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:52.3.0 build:trigger (input.hidden-input)
```

### Non-Core Packages

```
atom-runner 2.7.1 
build 0.67.0 
build-python 0.8.0 
busy 0.7.0 
ipython-exec 1.2.0 
python-tools 0.6.9 
```

**Comment by idleberg** [comment]
Thanks for reporting. Please update to v0.8.1

**Comment by pvince99** [comment]
thanks for the fix
