### ISSUE TITLE
Failed to activate the build-python package

### ISSUE THREAD

**Issue by dronn** [idleberg/atom-build-python#9]
[Enter steps to reproduce:]

1. Install build-python on atom
2. Computer shuts down due to lack of power
3. build-python package no longer activates

**Atom**: 1.14.1 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Home Premium 
**Thrown From**: [build-python](https://github.com/idleberg/atom-build-python) package 0.7.0

### Stack Trace

Failed to activate the build-python package

```
At Cannot find module 'atom-package-deps'

Error: Cannot find module 'atom-package-deps'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.14.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.satisfyDependencies (/packages/build-python/lib/provider.js:56:3)
    at Object.activate (/packages/build-python/lib/provider.js:48:10)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:814:28
```

### Commands

```
```

### Non-Core Packages

```
atom-runner 2.7.1 
build-python 0.7.0 
script 2.26.4 
```

**Comment by idleberg** [comment]
Did you install the package manually? If so, make sure to [install its dependencies](https://github.com/idleberg/atom-build-python#using-git).

**Comment by thecraftman** [comment]
PLease i am having this issue too on my ubuntu what can be done thanks
